import { spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { FixAttempt, Incident, ReviewResult, TriageResult } from "../types.ts";
import { formatInr } from "./cost.ts";

/**
 * PR body synthesized from the research dossier's survey of Seer, Copilot
 * Autofix, and OpenHands bodies: root cause, confidence, evidence,
 * reproduction test, change summary, verification, and an explicit
 * "what the agent did not do" risk section.
 */
export function buildPrBody(inc: Incident, triage: TriageResult, attempt: FixAttempt, review: ReviewResult | undefined): string {
  const lines: string[] = [];
  lines.push(`## Fixes ${inc.id} — ${inc.exceptionType}: ${truncate(inc.exceptionValue, 100)}`);
  lines.push(`_fingerprint \`${inc.fingerprint.slice(0, 12)}\`, ${inc.occurrences} occurrence${inc.occurrences === 1 ? "" : "s"}, first seen ${inc.firstSeen}_`);
  lines.push("");
  lines.push(`**Root cause:** ${triage.root_cause}`);
  lines.push(`**Confidence:** triage ${triage.confidence.toFixed(2)}${review ? ` · review ${review.confidence.toFixed(2)}` : ""}`);
  if (review?.open_question) lines.push(`**Open question for reviewers:** ${review.open_question}`);
  lines.push("");
  lines.push("### Evidence");
  for (const s of triage.suspects.slice(0, 5)) {
    lines.push(`- \`${s.file}${s.symbol ? `:${s.symbol}` : ""}\`${s.startLine ? ` (lines ${s.startLine}-${s.endLine})` : ""} — ${s.reason ?? ""} (score ${s.score})`);
  }
  if (inc.transaction) lines.push(`- Transaction: \`${inc.transaction}\``);
  lines.push("");
  lines.push("### Reproduction test");
  if (inc.reproduction) {
    lines.push(`\`${inc.reproduction.test_file}\` — **${inc.reproduction.test_name}**`);
    lines.push(`Fails on \`main\`: ${inc.reproduction.failure_summary}`);
    lines.push("Passes on this branch (see Verification).");
  }
  lines.push("");
  lines.push("### Change summary");
  lines.push(attempt.summary || attempt.hypothesis || "(no summary provided)");
  lines.push("");
  lines.push("### Verification");
  if (attempt.reproTest) lines.push(`- [x] reproduction test: ${attempt.reproTest.passed} passed / ${attempt.reproTest.failed} failed`);
  if (attempt.fullSuite) lines.push(`- [x] full suite: ${attempt.fullSuite.passed} passed / ${attempt.fullSuite.failed} failed (${attempt.fullSuite.durationMs}ms)`);
  for (const c of attempt.hardChecks) lines.push(`- [${c.ok ? "x" : " "}] ${c.name}${c.ok ? "" : ` — ${c.detail}`}`);
  if (review) lines.push(`- [${review.addresses_root_cause ? "x" : " "}] independent critic pass: addresses root cause, ${review.behavior_change_outside_crash_path ? "**behavior changed outside the crash path**" : "no behavior change outside the crash path"}`);
  lines.push("");
  lines.push("### What the agent did not do / risk notes");
  lines.push("- Did not touch test files, migrations, secrets, or other protected paths (guardrail-enforced, see blocks below if any).");
  for (const r of review?.risks ?? []) lines.push(`- ${r}`);
  if (attempt.attempt > 1) lines.push(`- This was attempt ${attempt.attempt} of up to 3; earlier attempts were reverted and are not in this diff.`);
  lines.push("");
  lines.push("### Provenance");
  lines.push(`Generated by PatchPilot run \`${inc.id}\` · ${attempt.filesChanged.length} file(s) changed · cost ${formatInr(inc.usage.inr)} (\$${inc.usage.usd.toFixed(4)})`);
  lines.push("");
  lines.push("A human reviews and merges this PR — PatchPilot never merges its own patches.");
  return lines.join("\n");
}

export function buildPrTitle(inc: Incident, triage: TriageResult): string {
  return `fix: ${truncate(triage.root_cause || inc.exceptionValue || inc.title, 72)}`;
}

/**
 * Opens a draft PR with `gh` when PATCHPILOT_OPEN_PR=1 and the repo has a
 * GitHub remote. Returns undefined (not an error) when `gh` or a remote is
 * unavailable — PR creation is optional, the patch and branch always exist.
 */
export async function openDraftPr(repoRoot: string, branch: string, title: string, body: string): Promise<{ url?: string; error?: string }> {
  // Body goes through a file: it's multi-line Markdown full of quotes and | > characters.
  const bodyFile = path.join(os.tmpdir(), `patchpilot-pr-${branch.replace(/[^\w-]/g, "_")}.md`);
  try {
    fs.writeFileSync(bodyFile, body, "utf8");
    await run("git", ["push", "-u", "origin", branch], repoRoot);
    const out = await run("gh", ["pr", "create", "--draft", "--title", title, "--body-file", bodyFile, "--head", branch], repoRoot);
    return { url: out.match(/https:\/\/\S+/)?.[0] };
  } catch (err) {
    return { error: (err instanceof Error ? err.message : String(err)).slice(0, 500) };
  } finally {
    fs.rmSync(bodyFile, { force: true });
  }
}

/** No shell: git and gh are real executables, and a shell would mangle arguments containing quotes or newlines. */
function run(cmd: string, args: string[], cwd: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd });
    let out = "";
    let err = "";
    child.stdout.on("data", (d) => (out += d));
    child.stderr.on("data", (d) => (err += d));
    child.on("close", (code) => (code === 0 ? resolve(out) : reject(new Error(err || out))));
    child.on("error", reject);
  });
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1) + "…" : s;
}
